export const state = {
  boards: [],
  validWords: [],
  remainingWords: [],
  hiddenLockId: null,
  currentPath: [],
  selectedLetters: [],
  completedBoards: [],
  currentBoard: null,
  lives: 3,
  scrolls: 0,
  resolvingLoss: false,
  isSelecting: false,
  vaultIndex: -1,
};
